export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const GET_AUTH_URL = 'GET_AUTH_URL'

export const GET_TV_SHOW = 'GET_TV_SHOW'
export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST'
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS'

export const FETCH_TRENDING_TV_SHOWS_REQUEST = 'FETCH_TRENDING_TV_SHOWS'
export const FETCH_TRENDING_TV_SHOWS_SUCCESS = 'FETCH_TRENDING_TV_SHOWS_SUCCESS'