export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const GET_TV_SHOW = 'GET_TV_SHOW'
export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST'
export const FETCH_SEARCH_SPECIFIC_REQUEST = 'FETCH_SEARCH_SPECIFIC_REQUEST'
export const FETCH_SEARCH_NEXT = 'FETCH_SEARCH_SUCCESS'
export const FETCH_SEARCH_PREV = 'FETCH_SEARCH_PREV'
export const FETCH_SEARCH_SPECIFIC = 'FETCH_SEARCH_SPECIFIC'
export const FETCH_SEARCH_FAIL = 'FETCH_SEARCH_FAIL'

export const SAVE_TV_SHOW = 'SAVE_TV_SHOW'

export const FETCH_TRENDING_TV_SHOWS_REQUEST = 'FETCH_TRENDING_TV_SHOWS'
export const FETCH_TRENDING_TV_SHOWS_SUCCESS = 'FETCH_TRENDING_TV_SHOWS_SUCCESS'